name 'concourse'
maintainer 'Brandon Raabe'
maintainer_email 'brandocorp@gmail.com'
license 'mit'
description 'Installs/Configures concourse'
long_description 'Installs/Configures concourse'
version '0.1.0'
